# Generated by scripts/brew_formula.py — do not hand-edit.
# All resources are pinned: pidrei's own from the release assets, third-party
# from uv.lock (the exact set the release's test suite ran against).
class Pidrei < Formula
  include Language::Python::Virtualenv

  desc "Terminal coding agent — a Python port of the pi coding agent"
  homepage "https://github.com/gi0baro/pidrei"
  url "https://github.com/gi0baro/pidrei/releases/download/v0.82.1.0/pidrei-0.82.1.0.tar.gz"
  sha256 "3c717fa67004b1763ec4b279aa43e64bb851ede580a583a2531f9e50f6432de5"
  license "MIT"

  # Free-threaded CPython is mandatory, not a preference.
  depends_on "python-freethreading"
  # The find and grep tools shell out to these; pidrei never downloads binaries.
  depends_on "fd"
  depends_on "ripgrep"
  # Resources build from sdists: tonio and cryptography are Rust extensions,
  # and cryptography links OpenSSL.
  depends_on "rust" => :build
  depends_on "openssl@3"
  # pillow compiles codecs against whatever its setup *detects*, and detection
  # reads the host's pkg-config while the sandboxed compile cannot see host
  # headers — a feature found-but-unreachable fails the whole build (seen with
  # the host's freetype/openjpeg on Linux). Declaring the full codec set makes
  # detection deterministic; jpeg/webp are also load-bearing for image paste.
  depends_on "freetype"
  depends_on "jpeg-turbo"
  depends_on "libtiff"
  depends_on "little-cms2"
  depends_on "openjpeg"
  depends_on "webp"
  uses_from_macos "zlib"

  on_linux do
    depends_on "libxcb"
  end

  resource "pidrei-ai" do
    url "https://github.com/gi0baro/pidrei/releases/download/v0.82.1.0/pidrei_ai-0.82.1.0.tar.gz"
    sha256 "6e2b46f771eb546048aa2ddab32035086da8a9d17eb3792b8c70705404f54c27"
  end

  resource "pidrei-agent" do
    url "https://github.com/gi0baro/pidrei/releases/download/v0.82.1.0/pidrei_agent-0.82.1.0.tar.gz"
    sha256 "d52bd24c699865d2baf4affda5b44607c46c7127d5d4403844032930ddaa958d"
  end

  resource "pidrei-tui" do
    url "https://github.com/gi0baro/pidrei/releases/download/v0.82.1.0/pidrei_tui-0.82.1.0.tar.gz"
    sha256 "85345e324786494db346387d71fece7840c118b895ee845c2c40bb561f3cee1e"
  end

  resource "pidrei-server" do
    url "https://github.com/gi0baro/pidrei/releases/download/v0.82.1.0/pidrei_server-0.82.1.0.tar.gz"
    sha256 "b71813bda1d8ad7e5567b3a25eee2eece0fb414ff4be199fa42adbae14d7948e"
  end

  resource "attrs" do
    url "https://files.pythonhosted.org/packages/9a/8e/82a0fe20a541c03148528be8cac2408564a6c9a0cc7e9171802bc1d26985/attrs-26.1.0.tar.gz"
    sha256 "d03ceb89cb322a8fd706d4fb91940737b6642aa36998fe130a9bc96c985eff32"
  end

  resource "botocore" do
    url "https://files.pythonhosted.org/packages/b9/cc/7f84a5d3071fe878380e9f610ab36ca87b8cbbc4aa81ba2727f90e1f3ea3/botocore-1.43.56.tar.gz"
    sha256 "6c01f85f0ff9863076f4c761e74ee3aa96c5ccc1ad09fc1efd62ef8f2d22bf57"
  end

  resource "cffi" do
    url "https://files.pythonhosted.org/packages/57/5f/ff100cae70ebe9d8df1c01a00e510e45d9adb5c1fdda84791b199141de97/cffi-2.1.0.tar.gz"
    sha256 "efc1cdd798b1aaf39b4610bba7aad28c9bea9b910f25c784ccf9ec1fa719d1f9"
  end

  resource "cryptography" do
    url "https://files.pythonhosted.org/packages/1f/99/d1c90d6041656cc6ee229dc99cd67fd0cd5aec3c5f7d72fffc27cc750054/cryptography-49.0.0.tar.gz"
    sha256 "f89660a348f4f78a92366240a61404e337586ef7f5909a2fef59ca88ef505493"
  end

  resource "grapheme" do
    url "https://files.pythonhosted.org/packages/ce/e7/bbaab0d2a33e07c8278910c1d0d8d4f3781293dfbc70b5c38197159046bf/grapheme-0.6.0.tar.gz"
    sha256 "44c2b9f21bbe77cfb05835fec230bd435954275267fea1858013b102f8603cca"
  end

  resource "httpunk" do
    url "https://files.pythonhosted.org/packages/bc/60/9db58e5fbe39a6e8563933d3e0ae06afe115c189dce298f9161b0482ff81/httpunk-0.1.2.tar.gz"
    sha256 "98c892670ad8cfd9f3f5dea9e1d1d2b434e1f5ba39cc47ad9bd43fc821f67e46"
  end

  resource "jieba" do
    url "https://files.pythonhosted.org/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz"
    sha256 "055ca12f62674fafed09427f176506079bc135638a14e23e25be909131928db2"
  end

  resource "jmespath" do
    url "https://files.pythonhosted.org/packages/d3/59/322338183ecda247fb5d1763a6cbe46eff7222eaeebafd9fa65d4bf5cb11/jmespath-1.1.0.tar.gz"
    sha256 "472c87d80f36026ae83c6ddd0f1d05d4e510134ed462851fd5f754c8c3cbb88d"
  end

  resource "jsonschema" do
    url "https://files.pythonhosted.org/packages/b3/fc/e067678238fa451312d4c62bf6e6cf5ec56375422aee02f9cb5f909b3047/jsonschema-4.26.0.tar.gz"
    sha256 "0c26707e2efad8aa1bfc5b7ce170f3fccc2e4918ff85989ba9ffa9facb2be326"
  end

  resource "jsonschema-specifications" do
    url "https://files.pythonhosted.org/packages/19/74/a633ee74eb36c44aa6d1095e7cc5569bebf04342ee146178e2d36600708b/jsonschema_specifications-2025.9.1.tar.gz"
    sha256 "b540987f239e745613c7a9176f3edb72b832a4ac465cf02712288397832b5e8d"
  end

  resource "linkify-it-py" do
    url "https://files.pythonhosted.org/packages/2e/c9/06ea13676ef354f0af6169587ae292d3e2406e212876a413bf9eece4eb23/linkify_it_py-2.1.0.tar.gz"
    sha256 "43360231720999c10e9328dc3691160e27a718e280673d444c38d7d3aaa3b98b"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/06/ff/7841249c247aa650a76b9ee4bbaeae59370dc8bfd2f6c01f3630c35eb134/markdown_it_py-4.2.0.tar.gz"
    sha256 "04a21681d6fbb623de53f6f364d352309d4094dd4194040a10fd51833e418d49"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/d6/54/cfe61301667036ec958cb99bd3efefba235e65cdeb9c84d24a8293ba1d90/mdurl-0.1.2.tar.gz"
    sha256 "bb413d29f5eea38f31dd4754dd7377d4465116fb207585f97bf925588687c1ba"
  end

  resource "partial-json-parser" do
    url "https://files.pythonhosted.org/packages/6a/6d/eed37d7ebc1e0bcd27b831c0cf1fe94881934316187c4b30d23f29ea0bd4/partial_json_parser-0.2.1.1.post7.tar.gz"
    sha256 "86590e1ba6bcb6739a2dfc17d2323f028cb5884f4c6ce23db376999132c9a922"
  end

  resource "pathspec" do
    url "https://files.pythonhosted.org/packages/5a/82/42f767fc1c1143d6fd36efb827202a2d997a375e160a71eb2888a925aac1/pathspec-1.1.1.tar.gz"
    sha256 "17db5ecd524104a120e173814c90367a96a98d07c45b2e10c2f3919fff91bf5a"
  end

  resource "pillow" do
    url "https://files.pythonhosted.org/packages/1c/3d/bb7fca845737cf9d7dbde16ed1843984665ff2e0a518f5db43e77ec540b9/pillow-12.3.0.tar.gz"
    sha256 "3b8182a766685eaa002637e28b4ec8d6b18819a0c71f579bf0dbaa5830297cce"
  end

  resource "punkreq" do
    url "https://files.pythonhosted.org/packages/6b/5d/6b0776cf01b41e021b873dc46b594ab822f41414d1f287d0109798c83419/punkreq-0.1.1.tar.gz"
    sha256 "a2fc4020c071067811f8fe4a844d5fa196daa78241616b57337384cb4013c104"
  end

  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/1b/7d/92392ff7815c21062bea51aa7b87d45576f649f16458d78b7cf94b9ab2e6/pycparser-3.0.tar.gz"
    sha256 "600f49d217304a5902ac3c37e1281c9fe94e4d0489de643a9504c5cdfdfc6b29"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/c3/b2/bc9c9196916376152d655522fdcebac55e66de6603a76a02bca1b6414f6c/pygments-2.20.0.tar.gz"
    sha256 "6757cd03768053ff99f3039c1a36d6c0aa0b263438fcab17520b30a303a82b5f"
  end

  resource "python-dateutil" do
    url "https://files.pythonhosted.org/packages/66/c0/0c8b6ad9f17a802ee498c46e004a0eb49bc148f2fd230864601a86dcf6db/python-dateutil-2.9.0.post0.tar.gz"
    sha256 "37dd54208da7e1cd875388217d5e00ebd4179249f90fb72437e91a35459a0ad3"
  end

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f"
  end

  resource "referencing" do
    url "https://files.pythonhosted.org/packages/22/f5/df4e9027acead3ecc63e50fe1e36aca1523e1719559c499951bb4b53188f/referencing-0.37.0.tar.gz"
    sha256 "44aefc3142c5b842538163acb373e24cce6632bd54bdb01b21ad5863489f50d8"
  end

  resource "rpds-py" do
    url "https://files.pythonhosted.org/packages/aa/2a/9618a122aeb2a169a28b03889a2995fe297588964333d4a7d67bdf46e147/rpds_py-2026.6.3.tar.gz"
    sha256 "1cebd1337c242e4ec2293e541f712b2da849b29f48f0c293684b71c0632625d4"
  end

  resource "six" do
    url "https://files.pythonhosted.org/packages/94/e7/b2c673351809dca68a0e064b6af791aa332cf192da575fd474ed7d6f16a2/six-1.17.0.tar.gz"
    sha256 "ff70335d468e7eb6ec65b95b99d3a2836546063f63acc5171de367e834932a81"
  end

  resource "tonio" do
    url "https://files.pythonhosted.org/packages/13/f6/045eb7ae9f164ed3fe2a8aa9180fc6dd8bac4c684a0ab3af4c89f2a05a39/tonio-0.9.2.tar.gz"
    sha256 "b1e004929104828ceb4c1e96ee4b8e8b29e34e3d0aede6377f82c0be625b69da"
  end

  resource "uc-micro-py" do
    url "https://files.pythonhosted.org/packages/78/67/9a363818028526e2d4579334460df777115bdec1bb77c08f9db88f6389f2/uc_micro_py-2.0.0.tar.gz"
    sha256 "c53691e495c8db60e16ffc4861a35469b0ba0821fe409a8a7a0a71864d33a811"
  end

  resource "uniseg" do
    url "https://files.pythonhosted.org/packages/fc/5e/fc5b1c370dc523a580cb214ee7753c8631a2d4be8fc51283785415b62d92/uniseg-0.10.1.tar.gz"
    sha256 "5224267916fc01132cb2f7bf60882402dde72ab52c6977184827e4d9d6676de6"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/53/0c/06f8b233b8fd13b9e5ee11424ef85419ba0d8ba0b3138bf360be2ff56953/urllib3-2.7.0.tar.gz"
    sha256 "231e0ec3b63ceb14667c67be60f2f2c40a518cb38b03af60abc813da26505f4c"
  end

  resource "websockets" do
    url "https://files.pythonhosted.org/packages/21/f7/bc3a25c5ec26ce62ce487690becc2f3710bbc7b33338f005ad390db0b986/websockets-16.1.1.tar.gz"
    sha256 "db234eda965dcce15df96bb9709f587cd87d4d52aaf0e80e2f34ec04c7670c57"
  end

  def install
    virtualenv_install_with_resources(using: "python3.14t")
  end

  test do
    assert_equal "0.82.1.0", shell_output("#{bin}/pidrei --version").strip
    # `--version` prints the bare version, no program name — on both binaries.
    assert_equal "0.82.1.0", shell_output("#{bin}/pi3 --version").strip
  end
end
